<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Guna.UI2">
      <HintPath>..\MoneyFlow.Desktop\lib\Guna.UI2.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyFlow.Core\MoneyFlow.Core.csproj" />
    <ProjectReference Include="..\MoneyFlow.Data\MoneyFlow.Data.csproj" />
    <ProjectReference Include="..\MoneyFlow.Services\MoneyFlow.Services.csproj" />
    <ProjectReference Include="..\MoneyFlow.Desktop\MoneyFlow.Desktop.csproj" />
  </ItemGroup>

</Project>
